/* eslint-disable import/prefer-default-export */
export const storeProducts = [
  {
    id: 1,
    title: 'Textured Ribbed Bomber Jacket',
    img: '@/assets/imgs/men/m-jacket1-big',
    price: 40.00,
    sex: 'm',
    category: 'Jackets',
    info: [
      'Ribbed sweat',
      'Baseball collar',
      'Zip opening',
      'Side pockets',
    ],
  },
  {
    id: 2,
    title: 'Nylon Biker Jacket',
    img: '@/assets/imgs/men/m-jacket2-big',
    price: 58.00,
    sex: 'm',
    category: 'Jackets',
    info: [
      'Smooth woven outer',
      'Stand-up collar',
      'Zip front fastening',
      'Functional pockets',
    ],
  },
  {
    id: 3,
    title: 'Jacket J-Eiko Nylon',
    img: '@/assets/imgs/men/m-jacket3-big',
    price: 175.00,
    sex: 'm',
    category: 'Jackets',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 4,
    title: 'Longline Sleeveless T-Shirt With Dropped Armhole And Print',
    img: '@/assets/imgs/men/m-tshirt1-big',
    price: 24.00,
    sex: 'm',
    category: 'T-Shirts',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 5,
    title: 'Longline T-Shirt With Aztec Yoke Print In Relaxed Skater Fit',
    img: '@/assets/imgs/men/m-tshirt2-big',
    price: 55.00,
    sex: 'm',
    category: 'T-Shirts',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 6,
    title: 'Sleeveless T-Shirt With Extreme Dropped Armholes And Applique',
    img: '@/assets/imgs/men/m-tshirt3-big',
    price: 60.00,
    sex: 'm',
    category: 'T-Shirts',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 7,
    title: 'Extreme Super Skinny Jeans With Knee Rips',
    img: '@/assets/imgs/men/m-jeans1-big',
    price: 20.00,
    sex: 'm',
    category: 'Jeans',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 8,
    title: 'Hyperflex Anbass Slim Fit Comfort Ultra Stretch Blue Wash',
    img: '@/assets/imgs/men/m-jeans2-big',
    price: 57.00,
    sex: 'm',
    category: 'Jeans',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 9,
    title: 'Jeans Arc 3d Slim Fit Colour Denim',
    img: '@/assets/imgs/men/m-jeans3-big',
    price: 70.00,
    sex: 'm',
    category: 'Jeans',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 10,
    title: 'Denim Shirt In Check with Short Sleeves',
    img: '@/assets/imgs/men/m-shirt1-big',
    price: 120.00,
    sex: 'm',
    category: 'Shirts',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 11,
    title: 'Formal Shirt In Slim Fit',
    img: '@/assets/imgs/men/m-shirt2-big',
    price: 90.00,
    sex: 'm',
    category: 'Shirts',
    info: [
      'Smooth fabric',
      'Stand collar with throat latch',
      'Ribbed shoulder panels',
      'Zip opening',
    ],
  },
  {
    id: 12,
    title: 'Boat Shoes in Leather',
    img: '@/assets/imgs/men/m-shoes1-big',
    price: 90.00,
    sex: 'm',
    category: 'Shoes',
    info: [
      '50% Real Leather, 50% Textile upper',
      'Matte, distressed finish',
      'Apron toe',
      'Slip-on style',
    ],
  },
  {
    id: 13,
    title: 'Elephant Print Cami Swing Dress',
    img: '@/assets/imgs/women/w-dress1-big',
    price: 90.00,
    sex: 'w',
    category: 'Dresses',
    info: [
      'Lightweight jersey',
      'Scoop neckline',
      'Relaxed fit',
      'Machine wash',
    ],
  },
  {
    id: 14,
    title: 'Embellished Dress',
    img: '@/assets/imgs/women/w-dress2-big',
    price: 70.00,
    sex: 'w',
    category: 'Dresses',
    info: [
      '50% Real Leather, 50% Textile upper',
      'Matte, distressed finish',
      'Apron toe',
      'Slip-on style',
    ],
  },
  {
    id: 15,
    title: 'Biker Jacket in Wool with Zip Detail',
    img: '@/assets/imgs/women/w-jacket1-big',
    price: 70.00,
    sex: 'w',
    category: 'Jackets',
    info: [
      '50% Real Leather, 50% Textile upper',
      'Matte, distressed finish',
      'Apron toe',
      'Slip-on style',
    ],
  },
  {
    id: 16,
    title: 'Embellished Dress',
    img: '@/assets/imgs/women/w-jacket2-big',
    price: 150.00,
    sex: 'w',
    category: 'Jackets',
    info: [
      '50% Real Leather, 50% Textile upper',
      'Matte, distressed finish',
      'Apron toe',
      'Slip-on style',
    ],
  },
  {
    id: 17,
    title: 'Bell Flare Jeans In Clean Black With Thigh Rips',
    img: '@/assets/imgs/women/w-jeans1-big',
    price: 30.00,
    sex: 'w',
    category: 'Jeans',
    info: [
      '50% Real Leather, 50% Textile upper',
      'Matte, distressed finish',
      'Apron toe',
      'Slip-on style',
    ],
  },
  {
    id: 18,
    title: 'Bell Flare Jeans In Clean Black With Thigh Rips',
    img: '@/assets/imgs/women/w-jeans2-big',
    price: 22.00,
    sex: 'w',
    category: 'Jeans',
    info: [
      '50% Real Leather, 50% Textile upper',
      'Matte, distressed finish',
      'Apron toe',
      'Slip-on style',
    ],
  },
];
